sudo: required

language: generic

os:
  - linux
  - osx

before_install:
  - sudo add-apt-repository --yes ppa:kalakris/cmake
  - sudo apt-get update -qq
  - sudo apt-get install cmake

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - clang

compiler:
  - gcc

script:
  - ./install.sh
  - sudo vim +PluginClean +qall
